### ISSUE TITLE
Unofficial Killing Floor 2 Patch settings not applied if used with SafeMutatorLoader

### ISSUE THREAD

**Issue by Stephen720** [GenZmeY/KF2-SafeMutLoader#8]
This is what my mutator list looks like
?Mutator=SML.Mut,KFUnofficialPatch.UKFPMutator,AAL.AALMut,YAS.YASMut,CTI.CTIMut,CVC.CVCMut,LTI.LTIMut,ZedSpawner.ZedSpawnerMut

When I use KFUnofficialPatch.UKFPMutator, I don't earn dosh for kills or at the end of a wave and none of my settings in KFUnofficialPatch.ini take affect.
using ?NoEDARs=1 and ?NoQPs=1 etc in the launch parameters also does not take affect. Making the mutator unusable.

Is it not possible for me to launch the unofficial patch by it's self since it's whitelisted and then use the safemutatorloader seperately so that all the mutators can be used?

**Comment by GenZmeY** [comment]
> When I use KFUnofficialPatch.UKFPMutator, I don't earn dosh for kills or at the end of a wave and none of my settings in KFUnofficialPatch.ini take affect.
> using ?NoEDARs=1 and ?NoQPs=1 etc in the launch parameters also does not take affect. Making the mutator unusable.

The last time I tested SML + UKFP it worked, but that was a very long time ago. Since then there have been several UKFP updates, maybe there are problems with this now.  

I'll look into this, but most likely the only thing I can do is remove UKFP from the list of compatible mutators because SML compatibility requires fixing UKFP, not SML. And I am not the author of UKFP ╮(￣_￣)╭  

> Is it not possible for me to launch the unofficial patch by it's self since it's whitelisted and then use the safemutatorloader seperately so that all the mutators can be used?

It won't work. UKFP title in steam workshop is misleading: UKFP is not actually whitelisted, it bypasses the whitelist verification system  
Users don't see the difference, but there is a difference in how it works and that's why we have problems with it, unfortunately

**Comment by GenZmeY** [comment]
However, I'll let you know if I come up with something, I have some thoughts

**Comment by GenZmeY** [comment]
Good news! It seems that the current version of UKFP no longer creates problems if it is loaded as a regular mutator. I've made the necessary changes to SML, now it should work fine with UKFP

Here is updated version:  
https://github.com/GenZmeY/KF2-SafeMutLoader/releases

**Comment by zeno0207** [comment]
good job
